# Generated by Django 5.2.6 on 2025-10-15 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_priority_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categorys', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='note',
            options={'verbose_name': 'Note', 'verbose_name_plural': 'Notes'},
        ),
        migrations.AlterModelOptions(
            name='subtask',
            options={'verbose_name': 'SubTask', 'verbose_name_plural': 'SubTasks'},
        ),
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='priority',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='parent_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='app.task'),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='title',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
